# ==========================================
# ???????????? ??????????
# ==========================================
spring.application.name=project-management-system
server.port=8080

# ==========================================
# ???????????? ???? ?????? (Docker PostgreSQL)
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5433/project_system
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# LIQUIBASE
# ==========================================
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml

# ==========================================
# HIBERNATE / JPA
# ==========================================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# THYMELEAF
# ==========================================
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# ==========================================
# ????????????
# ==========================================
spring.security.user.name=admin
spring.security.user.password=admin

# ==========================================
# ???????????
# ==========================================
logging.level.com.evdokimov.projectsystem=DEBUG
logging.level.org.springframework.security=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# ==========================================
# 2FA ????????
# ==========================================
twoFA.code.length=6
twoFA.code.expiration.minutes=5